import Head from "next/head"
import Header from "@/components/Header"
import Image from "next/image"
import { motion } from 'framer-motion'
import { client } from "@/libs/client"
import styles from '@/styles/Home.module.scss'


export type News = {
    id: string;
    title: string;
    content: string;
    category: Category;
    createdAt: string;
    updatedAt: string;
    publishedAt: string;
    revisedAt: string;
};

export type Category = {
    id: string;
    name: string;
}

export const getStaticProps = async (context: { params: { id: any } }) => {
    const id = context.params.id;
    const data = await client.get({ endpoint: "news", contentId: id });
    const createDate = new Date(Date.parse(data.publishedAt) + 32400000)
        .toLocaleDateString('ja-JP')
        .replace(/\//g, '/');

    return {
        props: {
            news: data,
            createDate,
        },
    };
};

export const getStaticPaths = async () => {
    const data = await client.get({ endpoint: "news" });
    const paths = data.contents.map((content: { id: any }) => `/news/${content.id}`);

    return {
        paths,
        fallback: false,
    };
};

type Props = {
    news: News;
    createDate: string;
};

export default function NewsId({ news, createDate }: Props) {
    var i = 0;
    return (
        <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
        >
            <div className="fixed top-0 left-0 w-full h-screen overflow-hidden z-[-1]">
                <Image className="object-cover" src="/reserve-bg.jpg" layout="fill" alt="" />
            </div>
            <Head>
                <title>NEWS | Beauty Salon 1</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <main className="text-white pt-16 md:pt-28">
                <div className="p-5" id="news">
                    <h1 className="text-6xl px-0 pb-10 font-bold md:px-14">NEWS</h1>
                    <div className="content">
                        <div className={styles.main}>
                            <p>{news.category.name}</p>
                            <h1 className={styles.title}>{news.title}</h1>
                            <p className={styles.publishedAt}>{createDate}</p>
                            <div dangerouslySetInnerHTML={{ __html: `${news.content}` }} className={styles.post}></div>

                            <a className=" my-5" href="../news">戻る</a>
                        </div>
                    </div>
                </div>
            </main>
        </motion.div >
    )
}