import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/components/Header'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Beauty Salon 1</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="home-bg">
        <Header />
        <div className="fixed w-full h-screen z-[-1] overflow-hidden">
          <Image className="object-cover" src="/sample1.jpg" layout="fill" alt="" />
        </div>
        <Footer />
      </main>
    </>
  )
}
