import Head from "next/head"
import Header from "@/components/Header"
import Image from "next/image"
import { motion } from 'framer-motion'

export default function Menu() {
    return (
        <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
        >
            <div className="fixed top-0 left-0 w-full h-screen overflow-hidden z-[-1]">
                <Image className="object-cover" src="/reserve-bg.jpg" fill alt="" />
            </div>
            <Head>
                <title>MENU | Beauty Salon 1</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <main className="text-white pt-16 md:pt-28">
                <div className="p-5" id="menu">
                    <h1 className="text-6xl px-0 pb-10 font-bold md:px-14">MENU</h1>
                    <div className="content">
                        <section className="border-b mb-6 md:mb-12 pb-6 md:pb-12 px-5 md:mx-16">
                            <h2 className="font-bold text-xl mb-7">CUT</h2>
                            <dl className="flex justify-between flex-wrap">
                                <dt className="w-1/2 mt-2">カット</dt>
                                <dd className="w-1/2 text-right mt-2">4180</dd>
                                <dt className="w-1/2 mt-2">スクールカット</dt>
                                <dd className="w-1/2 text-right mt-2">3630</dd>
                            </dl>
                        </section>
                        <section className="border-b mb-6 md:mb-12 pb-6 md:pb-12 px-5 md:mx-16">
                            <h2 className="font-bold text-xl mb-7">COLOR</h2>
                            <dl className="flex justify-between flex-wrap">
                                <dt className="w-1/2 mt-2">シングルカラー</dt>
                                <dd className="w-1/2 text-right mt-2">4730</dd>
                                <dt className="w-1/2 mt-2">イルミナカラー</dt>
                                <dd className="w-1/2 text-right mt-2">6930</dd>
                                <dt className="w-1/2 mt-2">オーガニックカラー</dt>
                                <dd className="w-1/2 text-right mt-2">6380</dd>
                                <dt className="w-1/2 mt-2">バレイヤージュカラー</dt>
                                <dd className="w-1/2 text-right mt-2">17600</dd>
                            </dl>
                        </section>
                        <section className="border-b mb-6 md:mb-12 pb-6 md:pb-12 px-5 md:mx-16">
                            <h2 className="font-bold text-xl mb-7">PARM</h2>
                            <dl className="flex justify-between flex-wrap">
                                <dt className="w-1/2 mt-2">ナチュラルウェーブ</dt>
                                <dd className="w-1/2 text-right mt-2">6600</dd>
                                <dt className="w-1/2 mt-2">デジタルパーマ</dt>
                                <dd className="w-1/2 text-right mt-2">11000</dd>
                            </dl>
                        </section>
                        <p className="text-sm px-5 md:mx-16">※税込み価格です。</p>
                    </div>
                </div>
            </main>
        </motion.div >
    )
}